### ISSUE TITLE
macOS - using wrong bundled ffmpeg libraries

### ISSUE THREAD

**Issue by RobertoD91** [codestation/qcma#103]
Hi, on macos 10.13.4 brew install ffmpeg in 
/usr/local/Cellar/ffmpeg/4.0
but qcma search only in
/usr/local/Cellar/ffmpeg/3.2/lib/
so app don't open and crash

qcma without ffmpeg work

**Comment by lordfriky** [comment]
Try using noffmpeg version

**Comment by RobertoD91** [comment]
yes, noffmpeg version work, i wrote it :)

but on "https://codestation.github.io/qcma/" it is recommended, for users with osx > 10.12,  to download the version with ffmpeg 

maybe you can leave only the noffmpeg version until the problem is fixed?

PS: sorry for my bad english

**Comment by StephDC** [comment]
While a REALLY DIRTY HACK of copying/linking the three required files into the old directory works as of now, I guess this is really an issue that warrants a new release, as the major version number changed for FFMPEG. It is VERY LIKELY there is some breaking API changes that may cause undefined behavior or crashes in the near future.

For those who installed FFMPEG (Ver. 4.0), you may try the following command to hopefully get it working temporarily.

```bash
sudo mkdir -p /usr/local/Cellar/ffmpeg/3.2/lib
cd /usr/local/Cellar/ffmpeg/3.2/lib
# IF USING Homebrew
export FFMPEGLIB=/usr/local/Cellar/ffmpeg/4.0/lib
# ELIF USING MacPorts
export FFMPEGLIB=/opt/local/lib
# FI
sudo ln -s ${FFMPEGLIB}/libavcodec.dylib libavcodec.57.dylib
sudo ln -s ${FFMPEGLIB}/libswresample.dylib libswresample.2.dylib
sudo ln -s ${FFMPEGLIB}/libavutil.dylib libavutil.55.dylib
```

Just to reiterate that this made the ffmpeg version work in my case, however it is a really dirty hack that it WILL cause problems later on due to the very likely API change of FFMPEG. If in doubt, just use the noffmpeg version as of now, and wait for a new release of QCMA.

BTW as I am using MacPorts I have to link/copy the libraries anyways, therefore it is less of an issue to me, but if you are already using Homebrew, I would rather recommend you to stay away from such trick.

**Comment by codestation** [comment]
Yea, the problem is that i bundled the ffmpeg libraries that i installed from homebrew but those are looking for their dependencies using a fixed path instead of a relative one.

Currently i only have a AMD processor (my Intel CPU died) and cannot run the macOS VM that i was using to rebuild a new version with newer ffmpeg (for now).

I am looking for some information before i can fix this bug and only distribute one version with ffmpeg included: either some ffmpeg libraries (not from Homebrew) that doesn't have absolute paths for their dependencies or some tool to change these paths on the ffmpeg libraries themselves.

**Comment by LoungeKatt** [comment]
https://evermeet.cx/ffmpeg/

Might be useful, might not. Not entirely sure if you were looking for binaries or source.

**Comment by codestation** [comment]
Yes, binaries are OK, now i need to find and prepare a macOS computer to rebuild Qcma using the new libraries.

**Comment by codestation** [comment]
Updated macOS release with newer Qt, ffmpeg (4.x) and fixed the dylib with https://github.com/arl/macdeployqtfix

The link is also on the releases tab
https://github.com/codestation/qcma/releases/download/v0.4.1/Qcma_0.4.1-1.dmg

**Comment by LoungeKatt** [comment]
I can confirm. Working as expected. Kudos.
