### ISSUE TITLE
Request - Release with latest changes

### ISSUE THREAD

**Issue by waltercool** [codestation/qcma#121]
No changes have been applied past months. Is there some possibility to make a release with all changes including removal of deprecated ffmpeg flags?

Thanks.

**Comment by waltercool** [comment]
Let me test some basic functions, like build, backup and restore.

**Comment by waltercool** [comment]
Correct. ffmpeg removed some deprecated flags, making unable to compile qcma.

Last changes made by codestation renamed those flags for the correct one.

**Comment by Vitnim** [comment]
So you just tested by compiling with the patch on Archlinux?  Or something else?  Is there a way I can test this without coding skills?

**Comment by codestation** [comment]
Gonna add a 0.4.2 tag after i find out why it fails to build under Ubuntu 18.10...

```
have choice for libavcodec58 = 7:4.0.2-2 needed by libavformat58: libavcodec-extra58 libavcodec58, 
have choice for libavcodec58 = 7:4.0.2-2 needed by libavcodec-dev: libavcodec-extra58 libavcodec58, 
have choice for libavcodec58 >= 7:4.0 | libavcodec-extra58 >= 7:4.0 needed by libchromaprint1: libavcodec-extra58 libavcodec58
```

**Comment by Vitnim** [comment]
Okay, so that was just about my limit for compiling source.  But in the end, I got waltercool's version to compile after spending a LONG time figuring out dependencies and '&@")! lrelease.  And it works!  Successfully built under fresh install of Ubuntu 18.10.  Haven't tested everything, but device connects and everything looks good.  Not sure I'd be much help, but if you want me to check anything on my Ubuntu system, let me know.
