### ISSUE TITLE
Cannot Connect to Vita

### ISSUE THREAD

**Issue by angelic-sedition** [codestation/qcma#21]
When I run qcma with a vita slim 3.15, I just keep getting a popup that says that the device has been disconnected. My other 3.01 vita slim works fine.

This is the output:
```
Starting QCMA v0.3.6-2-ga4662a1
Current locale: "en_US"
Cannot load translation for locale: "en_US"
Starting main thread: 0x00007f5c760cf780
Current desktop:  ""
Cannot load libqcma_appindicator plugin
No systemtrayicon available
Starting cma threads
Starting usb_thread: 0x00007f5c5ebd8700
Starting wireless_thread: 0x00007f5c5e3d7700
Waiting for wireless connection
VitaMTP: waiting for connection
PTP: Opening session
VitaMTP: Cannot read device name, tying to continue
Starting new USB connection
Vita connected: id 44712542209730C61
Cannot retreve device information.
Error while exchanging info with the vita
Releasing device...
Icon changed - disconnected
PTP: Opening session
VitaMTP: Cannot read device name, tying to continue
... (loops)
```

**Comment by jcgargma** [comment]
This sounds like the USB disconnection bug.
Reboot your Vita and try connecting again.

**Comment by angelic-sedition** [comment]
Does this happen often? This is the second or third time it's happened to me (thanks for pointing out the that rebooting fixes it; I didn't notice that's why it stopped happening last time).

**Comment by jcgargma** [comment]
Not that often.
I believe its related to having the USB connected before qcma is run, though I seem to also recall inducing it by refreshing the database while still connected.

**Comment by codestation** [comment]
Is a weird bug that happens frecuently on windows and causes the cma service on the Vita to lock up, thus cannot connect anymore until a device reset.

I now have access to a WIndows PC but sadly cannot reproduce this issue here (but i know that is a problem for a lot of users). I am gonna try to fix this when i have time but right now i am working on a rewrite of the cma+vitamtp portion of the app, the whole tcp/usb api is being redone so it can be debug more easily.

I don't have a fix right now for this problem but i am gonna leave the issue open until a solution is made (either the bugfix or the rewrite).

**Comment by sorgelig** [comment]
I'm not sure if it relative to the same issue, but i cannot connect my Vita second(!) time. i.e. i have to quit QCMA and start it again in order to connect my Vita again (if i disconnect Vita then i have to restart QCMA).
QCMA v0.3.6, Vita FW v3.36.

**Comment by codestation** [comment]
Try again with the latest version. Reopen the bug if the issue continues.
