### ISSUE TITLE
Segmentation fault during big transfer

### ISSUE THREAD

**Issue by Aryetis** [codestation/qcma#36]
Trying to do a backup using a .psvimg file triggers a segmentation fault randomly during the transfer.

Steps to recreate the bug:
1/ Create a HUGE .psvimg file on the pc (mine was around 33Gb)
2/ Backup using this file 

bug observed on : qcma 0.3.9 (debian jessie and windows version) or qcma_cli 0.3.9 debian jessie + vita2a(fat) on FW 3.51

Also using --verbose on debian jessie results in an immediate segmentation fault at startup.

Here is the log I obtain when using qcma_console --verbose under windows 8.0 (I've cut the boring parts):
http://pastebin.com/0FKdzFhW

ps : I initialy started this ticked because I downloaded the wrong package (wheezy for my debian jessie). So yeah, I'm recycling it

**Comment by Aryetis** [comment]
UPDATE : it always seems to hang up when hitting the file / object OHFI 268. Could it be that my backup file is corrupted ? Everything went fine during its creation. It's only the restoration that causes troubles.

**Comment by codestation** [comment]
Sorry for taking so long, every test takes between 20 mins and 1 hour (since the crash happens at any time after ~2GiB mark) and i have very little time per week to spend on this bug. I am starting to think that this is a 3.51 bug since i am also on it and have the same bug.

Hopefully i can spend some days on the upcoming holyday to solve this bug.

Sadly the only workaround that i can give for now is to avoid using the full backup/restore and backup/restore each game individually.

**Comment by Aryetis** [comment]
Yup I can imagine how painful it is ot debug that. To narrow your searches, know that I also tried to restore the backup file with opencma, and it failed too. 
Also I don't know what version of libvitamtp you're using but a similar-ish event error has been reported and fixed on the original libvitamtp github.

VitaMTP: PTP: reading event an error 0x02ff occurred
https://github.com/yifanlu/VitaMTP/issues/20

About the idea that it is a 3.51 specific bug.... I am obviously not ready to upgrade my psvita (for obvious reasons). And I agree with your workaround, but I used the restore/backup function to save my savefiles, which is impossible to do backing up game individually (stupid DRM --")

**Comment by codestation** [comment]
Did some tests today and it fails too with the official client so i am almost sure that is a 3.51 specific bug. Cannot say that the backup is corrupted since i managed to restore it successfully with opencma on three different times before it started failing just like qcma.

I have a couple of ideas left to do (besides a test on 3.55 if i manage to get a vita from a friend in the following days).

And yes, i started working on vitamtp from the latest version that yifanlu left to me to maintain.

**Comment by Aryetis** [comment]
Okay so I borrowed a 3.55 vita, and managed to restore my 33Gb backup on the first try. So yeah it's definetly a  "< 3.55" firmware issue.

**Comment by Aryetis** [comment]
Update : Just upgraded vita's firmware to 3.60 for reasons *wink wink*.
And the restore function worked great on the first time.
So yeah, definetly a 3.52 (or around) firmware related issue. Nothing can be done to fix that from QCMA.
Good luck to those reading that and still struggling.
