### ISSUE TITLE
Compatibility with Official Sony CMA

### ISSUE THREAD

**Issue by Xodiced** [codestation/qcma#46]
I checked for this information on the Wiki but it's empty (Do you need help with that?  If so I will contact you if you would like help filling it out, I've done Wiki work before for open source software), but I was wondering if the data created by QCMA is compatible with Sony's official Windows CMA?

Would I be able to restore a Vita/PS TV with data created by QCMA using Sony's CMA under Windows?

I have no issues with QCMA and do not plan on using Sony's CMA but this is just information that I was curious about.

Thanks.

**Comment by codestation** [comment]
I had a wiki made by a collaborator but he deleted his github account so is lost (i modified that wiki directly so i didn't keep a local repo of it).

Yes, both the individual and full backups can be used by both apps without changes. Fortunately the files arent modified by CMA (since they are already encrypted on the device) and the vitamtp protocol has been almost unchanged (if ever) in all those years so there aren't any compatibility problems.
