### ISSUE TITLE
FFmpeg doesn't seem compatible with Windows Vista and below

### ISSUE THREAD

**Issue by pyrohaze** [codestation/qcma#68]
qcma installation complete but when i run the program it says "the procedure entry point getNumaNodeProcessorMaskEx could not be located in the dynamic link library KERNEL32.dll and closes. any suggestions please

**Comment by codestation** [comment]
I investigated this and it seems that most prebuilt ffmpeg libraries are dropping vista support as well, probably because their end of extended support is only 6 months away.

I don't have the time to build ffmpeg from sources so i am stuck using official ffmpeg builds. If you find an official ffmpeg build (shared libraries) from the latest version with vista support then feel free to reopen this issue.

**Comment by pyrohaze** [comment]
Thanx for your kind info codestation, I read about ffmpeg Vista problems in some forum, I tried qcma older versions and they install and run well unlike the latest versions, no errors but they fail to detect ps vita, says ps vita not registered, since it was a problem of Vista, upgraded to seven, now it works fine. Thanx again
