### ISSUE TITLE
QCMA.exe won't close

### ISSUE THREAD

**Issue by StephanFS** [codestation/qcma#79]
So yeah, I have this problem with QCMA since the previous release (0.3.x)

When I close QCMA, it won't close at all. It stays open and the task manager won't terminate the process. I thought that this issue would be resolved in the new version, but it still persists.

What should I do? I'm using 0.4.1.

**Comment by codestation** [comment]
The only known bug is when you close Qcma and the Vita is still connected via USB (the problem comes from vitamtp). Qcma will show a message that tells you to disconnect your vita. This is your problem or a similar one?

**Comment by StephanFS** [comment]
It's very similar, but like I said, it won't close at all. It stays in the task manager and I can't use it again until I restart the PC manually, since I can't shutdown or restart via the Start Menu while QCMA.exe is still active in the task manager.

**Comment by codestation** [comment]
What is your OS? 64bit or 32bit? Currently cannot reproduce it on Windows 10 64bits, openSUSE 42.2 nor OSX Sierra.

Can you attach a log here? Open cmd and execute the following command (close qcma first):

"%PROGRAMFILES%\Qcma\qcma_console.exe" --with-debug > qcma_log.txt
Then connect your vita and try to reproduce the problem. Once it hangs, upload the log file. It will be located on c:\users\your_user

**Comment by StephanFS** [comment]
OS: 64 bit

Opened the QCMA Console, but the program didn't recognize my Vita. Here's the log.

[qcma_log.txt](https://github.com/codestation/qcma/files/644625/qcma_log.txt)

**Comment by StephanFS** [comment]
Found the problem, but I don't know how to solve it: it looks like my USB/SD card reader driver (Alcor Micro USB Card Reader 2.0) is causing some kind of interference with QCMA, forcing the program to become unkillable in the task manager.

**Comment by codestation** [comment]
The few ways that a program can become unkillable and/or unresponsive is because is waiting for a I/O operation to complete. Commonly seen with failing hard drives, but in your case seems  like is caused by that USB controller.

From the logs it seems to be stuck in the usb_thread loop. And since the logs never shows the "Finishing usb_thread" message then it got stuck in libusb code at the device enumeration.

Cannot help you more because i don't own that card reader to make more tests. The only thing that i can recommend is to use a real USB port that comes from the motherboard to see if it solves your problem.
